//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisapLine.MovimientoContable {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovimientoContable.MovContSoap")]
    public interface MovContSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaMovimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ConsultaMovimiento(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaMovimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ConsultaMovimientoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarMovimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegistrarMovimiento(string plnt, System.Data.DataTable dat, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarMovimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegistrarMovimientoAsync(string plnt, System.Data.DataTable dat, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Registrar(string plnt, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegistrarAsync(string plnt, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovContSoapChannel : VisapLine.MovimientoContable.MovContSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovContSoapClient : System.ServiceModel.ClientBase<VisapLine.MovimientoContable.MovContSoap>, VisapLine.MovimientoContable.MovContSoap {
        
        public MovContSoapClient() {
        }
        
        public MovContSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovContSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovContSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovContSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ConsultaMovimiento(string nombre) {
            return base.Channel.ConsultaMovimiento(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ConsultaMovimientoAsync(string nombre) {
            return base.Channel.ConsultaMovimientoAsync(nombre);
        }
        
        public string RegistrarMovimiento(string plnt, System.Data.DataTable dat, string path) {
            return base.Channel.RegistrarMovimiento(plnt, dat, path);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarMovimientoAsync(string plnt, System.Data.DataTable dat, string path) {
            return base.Channel.RegistrarMovimientoAsync(plnt, dat, path);
        }
        
        public string Registrar(string plnt, string path) {
            return base.Channel.Registrar(plnt, path);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarAsync(string plnt, string path) {
            return base.Channel.RegistrarAsync(plnt, path);
        }
    }
}
