//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisapLine.ComandCmd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComandCmd.ExecuteCmdSoap")]
    public interface ExecuteCmdSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _Command del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteCommand", ReplyAction="*")]
        VisapLine.ComandCmd.ExecuteCommandResponse ExecuteCommand(VisapLine.ComandCmd.ExecuteCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteCommand", ReplyAction="*")]
        System.Threading.Tasks.Task<VisapLine.ComandCmd.ExecuteCommandResponse> ExecuteCommandAsync(VisapLine.ComandCmd.ExecuteCommandRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteCommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteCommand", Namespace="http://tempuri.org/", Order=0)]
        public VisapLine.ComandCmd.ExecuteCommandRequestBody Body;
        
        public ExecuteCommandRequest() {
        }
        
        public ExecuteCommandRequest(VisapLine.ComandCmd.ExecuteCommandRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteCommandRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _Command;
        
        public ExecuteCommandRequestBody() {
        }
        
        public ExecuteCommandRequestBody(string _Command) {
            this._Command = _Command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteCommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteCommandResponse", Namespace="http://tempuri.org/", Order=0)]
        public VisapLine.ComandCmd.ExecuteCommandResponseBody Body;
        
        public ExecuteCommandResponse() {
        }
        
        public ExecuteCommandResponse(VisapLine.ComandCmd.ExecuteCommandResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteCommandResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteCommandResult;
        
        public ExecuteCommandResponseBody() {
        }
        
        public ExecuteCommandResponseBody(string ExecuteCommandResult) {
            this.ExecuteCommandResult = ExecuteCommandResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExecuteCmdSoapChannel : VisapLine.ComandCmd.ExecuteCmdSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteCmdSoapClient : System.ServiceModel.ClientBase<VisapLine.ComandCmd.ExecuteCmdSoap>, VisapLine.ComandCmd.ExecuteCmdSoap {
        
        public ExecuteCmdSoapClient() {
        }
        
        public ExecuteCmdSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecuteCmdSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteCmdSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteCmdSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisapLine.ComandCmd.ExecuteCommandResponse VisapLine.ComandCmd.ExecuteCmdSoap.ExecuteCommand(VisapLine.ComandCmd.ExecuteCommandRequest request) {
            return base.Channel.ExecuteCommand(request);
        }
        
        public string ExecuteCommand(string _Command) {
            VisapLine.ComandCmd.ExecuteCommandRequest inValue = new VisapLine.ComandCmd.ExecuteCommandRequest();
            inValue.Body = new VisapLine.ComandCmd.ExecuteCommandRequestBody();
            inValue.Body._Command = _Command;
            VisapLine.ComandCmd.ExecuteCommandResponse retVal = ((VisapLine.ComandCmd.ExecuteCmdSoap)(this)).ExecuteCommand(inValue);
            return retVal.Body.ExecuteCommandResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisapLine.ComandCmd.ExecuteCommandResponse> VisapLine.ComandCmd.ExecuteCmdSoap.ExecuteCommandAsync(VisapLine.ComandCmd.ExecuteCommandRequest request) {
            return base.Channel.ExecuteCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisapLine.ComandCmd.ExecuteCommandResponse> ExecuteCommandAsync(string _Command) {
            VisapLine.ComandCmd.ExecuteCommandRequest inValue = new VisapLine.ComandCmd.ExecuteCommandRequest();
            inValue.Body = new VisapLine.ComandCmd.ExecuteCommandRequestBody();
            inValue.Body._Command = _Command;
            return ((VisapLine.ComandCmd.ExecuteCmdSoap)(this)).ExecuteCommandAsync(inValue);
        }
    }
}
